import { Property } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Luxury Villa in Maitama',
    description: 'A stunning modern villa located in the prestigious Maitama district, featuring state-of-the-art amenities and a private pool.',
    price: 450000000,
    location: 'Maitama, Abuja',
    type: 'house',
    status: 'available',
    bedrooms: 6,
    bathrooms: 5,
    size_sqft: 5500,
    images: ['https://picsum.photos/seed/villa1/800/600', 'https://picsum.photos/seed/villa2/800/600'],
    agent_id: 'a1',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Modern Apartment in Asokoro',
    description: 'Exclusive luxury apartment in Asokoro with breathtaking views of the city and premium finishes.',
    price: 120000000,
    location: 'Asokoro, Abuja',
    type: 'apartment',
    status: 'available',
    bedrooms: 3,
    bathrooms: 3,
    size_sqft: 2500,
    images: ['https://picsum.photos/seed/penthouse1/800/600', 'https://picsum.photos/seed/penthouse2/800/600'],
    agent_id: 'a2',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Family Home in Gwarinpa',
    description: 'Spacious and secure family home in the heart of Gwarinpa, perfect for a growing family.',
    price: 85000000,
    location: 'Gwarinpa, Abuja',
    type: 'house',
    status: 'available',
    bedrooms: 4,
    bathrooms: 4,
    size_sqft: 3200,
    images: ['https://picsum.photos/seed/suburban1/800/600'],
    agent_id: 'a1',
    created_at: new Date().toISOString(),
  },
];
